FROM python:3.6
RUN pip install qtpy
RUN pip install numpy==1.15
RUN pip install PySide2==5.13
RUN python -m pip install requests
RUN pip install python-dateutil
RUN git clone https://github.com/sharppy/SHARPpy.git
WORKDIR /SHARPpy
RUN python setup.py install
CMD [ "python" ]
